spring:
  application:
    name: consumer
server:
  port: 8021
words:
  subjects: I,You,He,She,It
  verbs: ran,knew,had,saw,bought
  articles: a,the
  adjectives: reasonable,leaky,suspicious,ordinary,unlikely
  nouns: boat,book,vote,seat,backpack,partition,groundhog
